name: "Terraform Deploy"
on:
  push:
    branches:
      - main


jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Init
        run: |
          ls -l
          cd terraform-folder
          terraform init
      - name: Terraform Plan
        run: cd terraform-folder && terraform plan
      - name: Terraform Apply
        run: cd terraform-folder && terraform apply


